config/routes.rb
Rails.application.routes.draw do
  root to: 'messages#index'

  resources :messages, only: [:create] do
    collection do
      get :load
      # add post routes for turbo stream
      post :load
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/message.rb
class Message < ApplicationRecord
  validates_presence_of :sender, :body, :message_type
  after_create_commit lambda { |message|
    broadcast_append_to 'messages',
    partial: 'messages/partials/message_item',
    locals: { message: message }
  }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include SimpleService
  include TurboStreamHeader
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  def index; end

  def create
    return unless turbo_stream?

    run Service::MessageCreate
    render nothing: true
  end

  # create lazyload turbo frame on page loaded
  def load
    run Service::MessageList
    @messages = result
    @next_page = results[:query].next_page

    respond_to do |format|
      format.turbo_stream
      format.html
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DemoChatApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= stylesheet_pack_tag 'application', media: 'all' %>
    <%= javascript_pack_tag 'application' %>
  </head>

  <body>
    <div class="p-3 font-sans flex flex-col items-center justify-center w-full h-screen">
      <%= yield %>
    </div>
  </body>
</html>

app/views/messages/create.turbo_stream.erb
<% # Return handle by the Action cable %>

app/views/messages/index.html.erb
<div data-controller="main" class="max-w-lg w-full flex flex-col h-screen overflow-hidden">
  <%= turbo_stream_from 'messages' %>
  <%= turbo_frame_tag 'messages', src: load_messages_path, class: 'rounded-lg bg-royalblue-50 flex-grow w-full h-full px-3 py-4 text-center overflow-y-auto' %>
  <%= turbo_frame_tag 'new_message', target: 'messages' do %>
    <%= form_with model: Message.new, url: messages_path, data: { 'main-target': 'formMessage', action: 'turbo:submit-end->message#onFormMessageSubmit' } do |form| %>
      <%= render 'messages/partials/input_user', form: form %>
      <%= render 'messages/partials/compose_message', form: form %>
    <% end %>
  <% end %>
</div>

app/views/messages/load.html.erb
<%= turbo_frame_tag 'messages' do %>
  <% if @next_page %>
    <%= turbo_frame_tag 'load_more' do %>
      <%= form_with url: load_messages_path do |form| %>
        <%= form.hidden_field :page, value: @next_page %>
        <%= form.submit 'Load more', class: 'px-3 py-1 rounded-full mb-3 bg-royalblue-400 text-xs text-white font-bold cursor-pointer hover:bg-royalblue-500 focus:outline-none' %>
      <% end %>
    <% end %>
  <% end %>

  <% @messages.reverse.each do |message| %>
    <%= render 'messages/partials/message_item', message: message %>
  <% end %>
<% end %>

app/views/messages/load.turbo_stream.erb
<%= turbo_stream.replace 'load_more' do %>
  <% if @next_page %>
    <%= turbo_frame_tag 'load_more' do %>
      <%= form_with url: load_messages_path do |form| %>
        <%= form.hidden_field :page, value: @next_page %>
        <%= form.submit 'Load more', class: 'px-3 py-1 rounded-full mb-3 bg-royalblue-400 text-xs text-white font-bold cursor-pointer hover:bg-royalblue-500 focus:outline-none' %>
      <% end %>
    <% end %>
  <% end %>

  <% @messages.reverse.each do |message| %>
    <%= render 'messages/partials/message_item', message: message %>
  <% end %>
<% end %>

app/views/messages/partials/_compose_message.html.erb
<div data-controller="message" class="flex-grow flex flex-col overflow-hidden">
  <div class="hidden p-2" data-message-target="composeMessage">
    <%= form.text_field :body,
      placeholder: 'Type your message',
      data: {
        action: 'keyup->message#onInputMessageEnter',
        'message-target': 'inputMessage',
      },
      class: 'focus:outline-none shadow-inner rounded-full border focus:border-royalblue-300 border-black-100 px-5 py-3 flex-grow w-full'
    %>
    <%= form.submit 'Send', class: 'px-8 ml-2 rounded-full bg-royalblue-400 hover:bg-royalblue-500 transition-colors duration-300 text-white cursor-pointer' %>
  </div>
</div>

app/views/messages/partials/_input_user.html.erb
<div data-controller="user" class="mt-5">
  <div data-user-target="formUser" class="rounded-lg shadow-inner bg-royalblue-50 w-full px-5 py-8 text-center">
    <h3 class="mb-5 opacity-50">Welcome, Please input your name to start chatting!</h3>
    <%= form.text_field :sender,
          data: {
            action: 'keyup->user#onInputNameEnter',
            'user-target': 'inputName'
          },
          placeholder: 'Input your name',
          class: 'rounded-full focus:outline-none focus:border-royalblue-300 px-5 py-3 shadow-inner border max-w-sm w-full'
    %>
    <div class="text-xs mt-2 mb-5 opacity-50 italic">* Please input without space or symbols.</div>
    <a href="#" data-action="user#signIn" class="bg-royalblue-400 transition-colors duration-300 focus:outline-none hover:bg-royalblue-500 cursor-pointer px-8 py-3 rounded-lg shadow-sm text-white font-bold">
      Set name
    </a>
  </div>
  <div class="text-xs opacity-50 mb-1 text-left" data-user-target="welcomeMessage"></div>
</div>

app/views/messages/partials/_message_item.html.erb
<% if message.message_type == 'User'%>
  <div id="<%= dom_id message %>" data-controller="message-scroll" class="rounded-lg bg-royalblue-200 mb-2 py-2 px-3">
    <div class="font-bold text-xs opacity-25 text-left"><%= message.sender %>:</div>
    <div class="text-sm text-left opacity-75">
      <%= message.body %>
    </div>
    <div class="text-xs opacity-50 italic text-right">
      <span class="timeago" datetime="<%= message.created_at %>"></span>
    </div>
  </div>
<% else %>
  <div id="<%= dom_id message %>" data-controller="message-scroll" class="p-1 text-xs text-center opacity-25">
    <%= message.sender %> <%= message.body %> - <span class="timeago" datetime="<%= message.created_at %>"></span>
  </div>
<% end %>